/* The following code was generated by JFlex 1.7.0 */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>/home/death/Documentos/PUCRS/LP/T1_LDP/t1.lex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\12\0\1\1\1\3\1\3\1\2\35\0\1\27\1\0\1\11\1\5"+
    "\1\6\1\7\1\10\10\4\1\23\5\0\1\13\4\25\1\31\25\25"+
    "\2\12\1\24\5\12\1\14\1\12\1\30\2\12\1\17\4\12\1\16"+
    "\1\12\1\15\1\21\2\12\1\22\1\20\6\12\12\0\1\3\u05da\0"+
    "\12\26\206\0\12\26\306\0\12\26\u019c\0\12\26\166\0\12\26\166\0"+
    "\12\26\166\0\12\26\166\0\12\26\166\0\12\26\166\0\12\26\166\0"+
    "\12\26\166\0\12\26\166\0\12\26\140\0\12\26\166\0\12\26\106\0"+
    "\12\26\u0116\0\12\26\106\0\12\26\u0746\0\12\26\46\0\12\26\u012c\0"+
    "\12\26\200\0\12\26\246\0\12\26\6\0\12\26\266\0\12\26\126\0"+
    "\12\26\206\0\12\26\6\0\12\26\u03ce\0\1\3\1\3\u85f6\0\12\26"+
    "\u02a6\0\12\26\46\0\12\26\306\0\12\26\26\0\12\26\126\0\12\26"+
    "\u0196\0\12\26\u5316\0\12\26\u0586\0\12\26\u0bbc\0\12\26\200\0\12\26"+
    "\74\0\12\26\220\0\12\26\u0116\0\12\26\u0156\0\12\26\166\0\12\26"+
    "\u0176\0\12\26\146\0\12\26\146\0\12\26\u01a6\0\12\26\u0366\0\12\26"+
    "\u4e06\0\12\26\346\0\12\26\u6c74\0\62\26\u1150\0\12\26\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u16b5\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\10\1\2\2\15\0\1\3\102\0\2\4\1\0"+
    "\2\5\2\0\2\6\3\0\1\7\1\0\1\10\4\0"+
    "\2\11\21\0\2\12\2\13\3\0\1\14\11\0\2\15"+
    "\2\16";

  private static int [] zzUnpackAction() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\32\0\64\0\116\0\150\0\202\0\234\0\266"+
    "\0\320\0\352\0\64\0\u0104\0\u011e\0\u0138\0\234\0\u0152"+
    "\0\u016c\0\352\0\u0186\0\u01a0\0\150\0\u01ba\0\u01d4\0\u01ee"+
    "\0\u0208\0\64\0\u0222\0\u023c\0\u0256\0\u0270\0\u028a\0\u02a4"+
    "\0\u02be\0\u02d8\0\u02f2\0\u030c\0\u0326\0\u0340\0\u035a\0\u0374"+
    "\0\u038e\0\u03a8\0\u03c2\0\u03dc\0\u03f6\0\u0410\0\u042a\0\u0444"+
    "\0\u045e\0\u0478\0\u0492\0\u04ac\0\u04c6\0\u04e0\0\u04fa\0\u0514"+
    "\0\u052e\0\u0548\0\u0562\0\u057c\0\u0596\0\u05b0\0\u05ca\0\u05e4"+
    "\0\u05fe\0\u0618\0\u0632\0\u064c\0\u0666\0\u0680\0\u069a\0\u06b4"+
    "\0\u06ce\0\u06e8\0\u0702\0\u071c\0\u0736\0\u0750\0\u076a\0\u0784"+
    "\0\u079e\0\u07b8\0\u07d2\0\u07ec\0\u0806\0\u0820\0\u083a\0\u0854"+
    "\0\u086e\0\u0888\0\u08a2\0\u08bc\0\64\0\u08d6\0\u08f0\0\64"+
    "\0\u090a\0\u0924\0\u093e\0\64\0\u0958\0\u0972\0\u098c\0\u09a6"+
    "\0\64\0\u09c0\0\64\0\u09da\0\u09f4\0\u0a0e\0\u0a28\0\64"+
    "\0\u0a42\0\u0a5c\0\u0a76\0\u0a90\0\u0aaa\0\u0ac4\0\u0ade\0\u0af8"+
    "\0\u0b12\0\u0b2c\0\u0b46\0\u0b60\0\u0b7a\0\u0b94\0\u0bae\0\u0bc8"+
    "\0\u0be2\0\u0bfc\0\64\0\u0c16\0\64\0\u0c30\0\u0c4a\0\u0c64"+
    "\0\u0c7e\0\64\0\u0c98\0\u0cb2\0\u0ccc\0\u0ce6\0\u0d00\0\u0d1a"+
    "\0\u0d34\0\u0d4e\0\u0d68\0\64\0\u0d82\0\64\0\u0d9c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\36\3\1\4\1\5\1\3\2\4\1\6\1\7\1\3"+
    "\3\7\1\10\3\7\1\3\1\7\1\11\1\12\1\6"+
    "\1\7\1\11\33\0\1\13\1\14\1\13\1\15\1\16"+
    "\1\0\2\15\1\0\1\17\1\20\7\17\1\0\1\21"+
    "\1\17\1\22\1\0\2\23\4\0\1\24\2\0\2\24"+
    "\15\0\1\24\7\0\1\22\1\25\1\0\2\22\15\0"+
    "\1\22\7\0\1\17\1\26\1\0\2\17\1\0\1\17"+
    "\1\20\7\17\1\0\2\17\2\0\2\17\4\0\1\17"+
    "\1\26\1\0\2\17\1\0\1\17\1\20\4\17\1\27"+
    "\2\17\1\0\2\17\2\0\2\17\4\0\1\17\1\26"+
    "\1\0\2\17\1\0\1\17\1\20\7\17\1\0\1\17"+
    "\1\30\2\0\1\17\1\30\1\0\1\13\1\14\1\13"+
    "\1\22\1\24\1\0\2\22\15\0\1\22\1\0\2\31"+
    "\1\0\1\32\31\0\1\13\1\14\1\13\1\33\1\34"+
    "\1\0\2\33\1\0\1\17\1\20\7\17\1\0\1\21"+
    "\1\17\1\22\1\0\2\23\1\0\1\13\1\14\1\13"+
    "\1\35\1\36\1\0\2\35\2\0\1\20\12\0\1\24"+
    "\1\0\2\31\12\0\1\37\1\0\7\37\1\0\2\37"+
    "\2\0\2\37\4\0\1\40\1\26\1\0\2\40\1\0"+
    "\1\17\1\20\7\17\1\0\2\17\2\0\2\17\4\0"+
    "\1\41\1\26\1\0\2\41\1\42\1\17\1\20\7\17"+
    "\1\0\2\17\1\43\1\42\2\17\1\0\1\13\1\14"+
    "\1\13\1\24\2\0\2\24\15\0\1\24\1\0\2\31"+
    "\5\0\1\36\5\0\1\20\22\0\1\17\1\26\1\0"+
    "\2\17\1\0\1\17\1\20\4\17\1\44\2\17\1\0"+
    "\2\17\2\0\2\17\4\0\1\17\1\26\1\0\2\17"+
    "\1\0\1\17\1\20\7\17\1\0\1\17\1\45\2\0"+
    "\1\17\1\45\4\0\1\43\2\0\2\43\1\42\14\0"+
    "\1\43\1\42\3\0\1\13\1\14\1\13\1\46\1\16"+
    "\1\0\2\46\1\0\1\17\1\20\7\17\1\0\1\21"+
    "\1\17\1\22\1\0\2\23\1\0\1\13\1\14\1\13"+
    "\1\47\1\36\1\0\2\47\2\0\1\20\12\0\1\24"+
    "\1\0\2\31\1\0\1\13\1\14\1\13\1\50\1\51"+
    "\1\0\2\50\13\0\1\51\1\0\1\24\1\0\2\31"+
    "\5\0\1\52\5\0\1\20\16\0\1\53\3\0\6\53"+
    "\1\54\1\53\7\54\1\53\2\54\2\53\2\54\4\0"+
    "\1\55\1\56\1\0\2\55\1\0\1\17\1\20\7\17"+
    "\1\0\1\57\1\17\2\0\2\17\1\0\1\13\1\14"+
    "\1\13\1\41\1\26\1\0\2\41\1\0\1\17\1\20"+
    "\7\17\1\0\2\17\1\43\1\0\2\17\4\0\1\43"+
    "\2\0\2\43\15\0\1\43\4\0\1\13\1\14\1\13"+
    "\1\43\2\0\2\43\15\0\1\43\7\0\1\17\1\26"+
    "\1\0\2\17\1\0\1\17\1\20\5\17\1\60\1\17"+
    "\1\0\2\17\2\0\2\17\4\0\1\61\1\26\1\0"+
    "\2\61\1\0\1\17\1\20\7\17\1\0\2\17\1\62"+
    "\1\0\2\17\1\0\1\13\1\14\1\13\1\63\1\64"+
    "\1\0\2\63\1\65\1\17\1\20\7\17\1\0\2\17"+
    "\1\22\1\0\2\23\1\0\1\13\1\14\1\13\1\66"+
    "\1\51\1\0\2\66\13\0\1\51\1\0\1\24\1\0"+
    "\2\31\1\0\1\13\1\14\1\13\1\67\1\51\1\0"+
    "\2\67\13\0\1\51\1\0\1\24\1\0\2\31\4\0"+
    "\1\70\2\0\2\70\34\0\1\20\32\0\1\71\15\0"+
    "\1\53\3\0\6\53\1\54\1\53\1\72\6\54\1\53"+
    "\2\54\2\53\2\54\4\0\1\73\1\56\1\0\2\73"+
    "\1\0\1\17\1\20\7\17\1\0\1\57\1\17\2\0"+
    "\2\17\4\0\1\70\1\36\1\0\2\70\2\0\1\20"+
    "\22\0\1\74\1\26\1\0\2\74\1\0\1\17\1\20"+
    "\7\17\1\0\2\17\2\0\2\17\4\0\1\17\1\26"+
    "\1\0\2\17\1\0\1\17\1\20\6\17\1\75\1\76"+
    "\2\17\2\0\2\17\4\0\1\17\1\26\1\0\2\17"+
    "\1\0\1\17\1\20\7\17\1\0\1\17\1\77\2\0"+
    "\1\17\1\77\25\0\1\100\3\0\1\100\1\0\1\13"+
    "\1\14\1\13\1\101\1\64\1\0\2\101\1\0\1\17"+
    "\1\20\7\17\1\0\2\17\1\22\1\0\2\23\1\0"+
    "\1\13\1\14\1\13\1\24\1\36\1\0\2\24\2\0"+
    "\1\20\12\0\1\24\1\0\2\31\4\0\1\102\2\0"+
    "\2\102\22\0\1\13\1\14\1\13\1\103\1\51\1\0"+
    "\2\103\13\0\1\51\1\0\1\24\1\0\2\31\1\0"+
    "\1\13\1\14\1\13\1\24\1\51\1\0\2\24\13\0"+
    "\1\51\1\0\1\24\1\0\2\31\4\0\1\104\1\105"+
    "\1\0\2\104\13\0\1\105\22\0\1\106\14\0\1\53"+
    "\3\0\6\53\1\54\1\53\1\72\1\107\5\54\1\53"+
    "\2\54\2\53\2\54\4\0\1\17\1\56\1\0\2\17"+
    "\1\0\1\17\1\20\7\17\1\0\1\57\1\17\2\0"+
    "\2\17\4\0\1\110\1\111\1\0\2\110\1\0\1\17"+
    "\1\20\7\17\1\0\1\112\1\17\2\0\2\17\4\0"+
    "\1\17\1\26\1\0\2\17\1\0\1\17\1\20\7\17"+
    "\1\76\2\17\2\0\2\17\6\0\1\113\15\0\1\113"+
    "\11\0\1\114\1\26\1\0\2\114\1\0\1\17\1\20"+
    "\7\17\1\0\2\17\1\115\1\0\2\17\4\0\1\115"+
    "\2\0\2\115\15\0\1\115\4\0\1\13\1\14\1\13"+
    "\1\116\1\64\1\0\2\116\1\0\1\17\1\20\7\17"+
    "\1\0\2\17\1\22\1\0\2\23\4\0\1\117\2\0"+
    "\2\117\22\0\1\13\1\14\1\13\1\24\1\120\1\0"+
    "\2\24\13\0\1\51\1\0\1\24\1\0\2\31\4\0"+
    "\1\121\1\105\1\0\2\121\13\0\1\105\11\0\1\122"+
    "\2\0\2\122\37\0\1\123\13\0\1\53\3\0\6\53"+
    "\1\54\1\53\1\72\1\54\1\124\4\54\1\53\2\54"+
    "\2\53\2\54\4\0\1\125\1\111\1\0\2\125\1\0"+
    "\1\17\1\20\7\17\1\0\1\112\1\17\2\0\2\17"+
    "\4\0\1\122\1\36\1\0\2\122\2\0\1\20\22\0"+
    "\1\126\1\26\1\0\2\126\1\0\1\17\1\20\7\17"+
    "\1\0\2\17\2\0\2\17\6\0\1\127\15\0\1\127"+
    "\11\0\1\130\1\26\1\0\2\130\1\0\1\17\1\20"+
    "\7\17\1\0\2\17\1\131\1\0\2\17\4\0\1\131"+
    "\2\0\2\131\15\0\1\131\4\0\1\13\1\14\1\13"+
    "\1\132\1\64\1\0\2\132\1\0\1\17\1\20\7\17"+
    "\1\0\2\17\1\22\1\0\2\23\4\0\1\133\2\0"+
    "\2\133\25\0\1\134\2\0\2\134\26\0\1\105\16\0"+
    "\1\105\6\0\1\135\1\136\1\135\1\137\2\0\2\137"+
    "\22\0\1\140\1\141\1\140\26\0\1\53\1\140\1\141"+
    "\1\140\6\53\1\54\1\53\1\72\6\54\1\53\2\54"+
    "\2\53\2\54\4\0\1\17\1\111\1\0\2\17\1\0"+
    "\1\17\1\20\7\17\1\0\1\112\1\17\2\0\2\17"+
    "\1\0\1\135\1\136\1\135\1\142\1\26\1\0\2\142"+
    "\1\0\1\17\1\20\7\17\1\0\2\17\2\0\2\17"+
    "\4\0\1\143\2\0\2\143\1\0\1\143\1\0\7\143"+
    "\1\0\2\143\2\0\2\143\1\0\1\144\1\145\1\144"+
    "\1\17\1\26\1\0\2\17\1\0\1\17\1\20\7\17"+
    "\1\0\2\17\2\0\2\17\1\0\1\144\1\145\1\144"+
    "\27\0\1\13\1\14\1\13\1\146\1\64\1\0\2\146"+
    "\1\0\1\17\1\20\7\17\1\0\2\17\1\22\1\0"+
    "\2\23\4\0\1\147\2\0\2\147\25\0\1\150\1\105"+
    "\1\0\2\150\13\0\1\105\6\0\1\151\31\0\1\135"+
    "\1\136\1\135\1\152\2\0\2\152\22\0\1\153\31\0"+
    "\1\135\1\136\1\135\1\154\1\26\1\0\2\154\1\0"+
    "\1\17\1\20\7\17\1\0\2\17\2\0\2\17\4\0"+
    "\1\143\1\155\1\0\2\143\1\0\1\143\1\0\7\143"+
    "\1\0\1\156\1\143\2\0\2\143\1\0\1\144\31\0"+
    "\1\13\1\14\1\13\1\157\1\64\1\0\2\157\1\0"+
    "\1\17\1\20\7\17\1\0\2\17\1\22\1\0\2\23"+
    "\1\0\1\160\1\161\1\160\5\0\1\162\24\0\1\163"+
    "\1\105\1\0\2\163\13\0\1\105\6\0\1\135\1\136"+
    "\1\135\27\0\1\135\1\136\1\135\1\17\1\26\1\0"+
    "\2\17\1\0\1\17\1\20\7\17\1\0\2\17\2\0"+
    "\2\17\14\0\1\164\21\0\1\143\1\155\1\0\2\143"+
    "\1\0\1\143\1\0\1\165\6\143\1\0\1\156\1\143"+
    "\2\0\2\143\1\0\1\13\1\14\1\13\1\166\1\64"+
    "\1\0\2\166\1\0\1\17\1\20\7\17\1\0\2\17"+
    "\1\22\1\0\2\23\1\0\1\160\34\0\1\167\2\0"+
    "\2\167\26\0\1\105\1\170\15\0\1\105\22\0\1\171"+
    "\20\0\1\143\1\155\1\0\2\143\1\0\1\143\1\0"+
    "\1\143\1\172\5\143\1\0\1\156\1\143\2\0\2\143"+
    "\1\0\1\13\1\14\1\13\1\173\1\64\1\0\2\173"+
    "\1\0\1\17\1\20\7\17\1\0\2\17\1\22\1\0"+
    "\2\23\4\0\1\174\2\0\2\174\30\0\1\175\40\0"+
    "\1\176\17\0\1\143\1\155\1\0\2\143\1\0\1\143"+
    "\1\0\2\143\1\177\4\143\1\0\1\156\1\143\2\0"+
    "\2\143\1\0\1\13\1\14\1\13\1\200\1\64\1\0"+
    "\2\200\1\0\1\17\1\20\7\17\1\0\2\17\1\22"+
    "\1\0\2\23\4\0\1\201\2\0\2\201\30\0\1\202"+
    "\23\0\1\203\1\204\1\203\27\0\1\203\1\204\1\203"+
    "\1\143\1\155\1\0\2\143\1\0\1\143\1\0\7\143"+
    "\1\0\1\156\1\143\2\0\2\143\1\0\1\205\1\206"+
    "\1\205\1\207\1\64\1\0\2\207\1\0\1\17\1\20"+
    "\7\17\1\0\2\17\1\22\1\0\2\23\4\0\1\210"+
    "\2\0\2\210\30\0\1\211\23\0\1\212\31\0\1\205"+
    "\31\0\1\13\1\14\1\13\1\207\1\64\1\0\2\207"+
    "\1\0\1\17\1\20\7\17\1\0\2\17\1\22\1\0"+
    "\2\23\11\0\1\213\30\0\1\214\25\0\1\215\2\0"+
    "\2\215\32\0\1\216\24\0\1\217\2\0\2\217\25\0"+
    "\1\220\2\0\2\220\25\0\1\221\2\0\2\221\25\0"+
    "\1\222\2\0\2\222\25\0\1\223\2\0\2\223\22\0"+
    "\1\224\1\225\1\224\27\0\1\226\1\227\1\226\27\0"+
    "\1\224\31\0\1\226\30\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3510];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\7\1\1\11\1\1\15\0\1\11\102\0"+
    "\1\11\1\1\1\0\1\11\1\1\2\0\1\11\1\1"+
    "\3\0\1\11\1\0\1\11\4\0\1\11\1\1\21\0"+
    "\1\11\1\1\1\11\1\1\3\0\1\11\11\0\1\11"+
    "\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[151];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 328) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':  // fall through
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.print(yytext());
            } 
            // fall through
          case 15: break;
          case 2: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { System.out.println("Números Reais");
            } 
            // fall through
          case 16: break;
          case 3: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { System.out.println("Números Reais");
            } 
            // fall through
          case 17: break;
          case 4: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { System.out.println("IP");
            } 
            // fall through
          case 18: break;
          case 5: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { System.out.println("Email");
            } 
            // fall through
          case 19: break;
          case 6: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 7);
            { System.out.println("Placa Mercosul");
            } 
            // fall through
          case 20: break;
          case 7: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { System.out.println("IP");
            } 
            // fall through
          case 21: break;
          case 8: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { System.out.println("Email");
            } 
            // fall through
          case 22: break;
          case 9: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 9);
            { System.out.println("Telefone fixo");
            } 
            // fall through
          case 23: break;
          case 10: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -1);
            { System.out.println("URL");
            } 
            // fall through
          case 24: break;
          case 11: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 13);
            { System.out.println("ISBN");
            } 
            // fall through
          case 25: break;
          case 12: 
            // lookahead expression with fixed lookahead length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzMarkedPos, -2);
            { System.out.println("URL");
            } 
            // fall through
          case 26: break;
          case 13: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 18);
            { System.out.println("CNPJ");
            } 
            // fall through
          case 27: break;
          case 14: 
            // lookahead expression with fixed base length
            zzMarkedPos = Character.offsetByCodePoints
                (zzBufferL, zzStartRead, zzEndRead - zzStartRead, zzStartRead, 19);
            { System.out.println("Cartão de Crédito");
            } 
            // fall through
          case 28: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Yylex [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Yylex scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Yylex(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
